--- 
title:  "MATH2750 Introduction to Markov Processes"
author: "[Matthew Aldridge](mailto:m.aldridge@leeds.ac.uk)"
date:   "University of Leeds, 2020--2021"
site:   bookdown::bookdown_site
description: "Lecture notes for the course MATH2750 Introduction to Markov Process at the University of Leeds, 2020--2021"
favicon: favicon.ico
url:    https://mpaldridge.github.io/math2750/
---

# Schedule {.unnumbered #home}


::: {.mysched}
**Week 6** (8--12 March):

* [**Section 13**: Poisson process with Poisson increments](#S13-poisson-poisson)
* [**Section 14**: Poisson process with exponential holding times](#S14-poisson-exponential)
* [**Problem Sheet 7**](#P07)
* [**Computational Worksheet 2 / Assessment 2**](#computing): computational drop-in sessions this week, due 18 March
* [**Assessment 3**](#A3): due 25 March
* **Lecture**: Tuesday at 1400 (Zoom)
* **Workshops** on Problem Sheet 6: Monday or Tuesday (Zoom)
* **Computational drop-in sessions**: Monday, Tuesday or Wedenesday (Teams)
* **Drop-in sessions**: Tuesday or Wednesday (Teams)
:::

::: {.oldsched}
**Week 6** (1--5 March):

* [**Section 11**: Long-term behaviour of Markov chians](#S11-long-term-chains)
* [**Section 12**: End of of Part I: Discrete time Markov chains](#S12-revision-i)
* [**Problem Sheet 6**](#P06)
* [**Computational Worksheet 2 / Assessment 2**](#computing): computational drop-in sessions next week, due 18 March
* [**Assessment 3**](#A3): due 25 March
:::

::: {.oldsched}
**Week 5** (22--26 February):

* [**Section 9**: Recurrence and transience](#S09-recurrence-transience)
* [**Section 10**: Stationary distributions](#S10-stationary-distributions)
* [**Problem Sheet 5**](#P05)
* [**Computational Worksheet 1**](#computing)
:::

::: {.oldsched}
**Week 4** (15--19 February):

* [**Section 7**: Class Structure](#S07-classes)
* [**Section 8**: Hitting times](#S08-hitting-times)
* [**Problem Sheet 4**](#P04)
* [**Computational Worksheet 1**](#computing), with computational drop-in sessions
:::

::: {.oldsched}
**Week 3** (8--12 February):

* [**Section 5**: Discrete time Markov chains](#S05-markov-chains)
* [**Section 6**: Examples from actuarial science](#S06-examples)
* [**Problem Sheet 3**](#P03)
* [**Assessment 1**](#A1) due Thursday 11 February (this week) at 1400
* [**Computational Worksheet 1**](#computing): computational drop-in sessions next week
:::

::: {.oldsched}
**Week 2** (1--5 February):

* [**Section 3**: Gambler's ruin](#S03-gamblers-ruin)
* [**Section 4**: Linear difference equations](#S04-ldes)
* [**Problem Sheet 2**](#P02)
* [**Assessment 1**](#A1) due Thursday 11 February (next week) at 1400
:::

::: {.oldsched}
**Week 1** (25--29 January):

* [About the module](#S00-about)
* [**Section 1**: Stochastic processes and the Markov property](#S01-stochastic-processes)
* [**Section 2**: Random walks](#S02-random-walk)
* [**Problem Sheet 1**](#P01)
:::