# Assessment 4 {.unnumbered #A4}


::: {.mysummary}
This assessment counts as 4% of your final module grade. You should attempt both questions. You must show your working, and there are marks for the quality of your mathematical writing.

The deadline for submission is **Thursday 6 May at 2pm**. Submission will be to Gradescope via Minerva, from Tuesday 4 May. It would be helpful to start your solution to Question 2 on a new page. If you hand-write your solutions and scan them using your phone, please convert to PDF using a proper scanning app (I like Microsoft Office Lens or Adobe Scan); please don't submit images or photographs.

Late submissions up to Thursday 13 May at 2pm will still be marked, but	the total mark will be reduced by 10% per day or part-day for which the work is late. Submissions are not permitted after Thursday 13 May.

Your solutions to this assessment should be your own work. Copying, collaboration or plagiarism are not permitted. Asking others to do your work, including via the internet, is not permitted. Transgressions are considered to be a very serious matter, and will be dealt with according to the University's disciplinary procedures.
:::

:::: {.myq}
**1.** The arrival of buses is modelled as a Poisson process with rate $\lambda = 4$ per hour.

::: {.subq}
**(a)** What is the expected number of buses that arrive in a two-hour period?
[[1 mark]]{style="float:right"}
:::
::: {.subq}
**(b)** What is the probability that at least two buses arrives in a half hour period.
[[1]]{style="float:right"}
:::
::: {.subq}
**(c)** I arrive at the bus stop and start my watch. What is the expected amount
of time until the sixth bus arrives. What is the standard deviation of this
time? [[2]]{style="float:right"}
:::
::: {.subq}
**(d)** Given that exactly two buses arrive between 2pm and 3pm, what is the
expected arrival time of the first bus? [[2]]{style="float:right"}
:::
::: {.subq}
**(e)** I arrive at the bus stop at 4pm. What is the expected inter-arrival time
between the previous bus that I missed and the next bus to arrive that I
catch? [[1]]{style="float:right"}
:::
::: {.subq}
**(f)** I want to get the number 6 bus. Each bus that arrives is a number 6 bus
independently with probability 0.25. What is the expected amount of time
to wait until a number 6 bus? [[1]]{style="float:right"}
:::
::: {.subq}
**(g)** What is the probability that at least two buses arrive in a one hour period, at least one of which is a number 6 bus? [[2]]{style="float:right"}
:::
::::


::: {.myq}
**2.** Consider the Markov jump process with generator matrix
\[ \mathsf Q = \begin{pmatrix}
-2 &  2 &  0 &  0 &  0 \\
 3 & -3 &  0 &  0 &  0 \\
 0 &  1 & -2 &  1 &  0 \\
 0 &  0 &  3 & -5 &  2 \\
 0 & 0 & 0 & 0 & 0
\end{pmatrix} , \]
and let $(\mathsf P(t))$ be the associated transition semigroup. Find $\lim_{t \to \infty} \mathsf P(t)$.  [[10]]{style="float:right"}

*Note: The majority of the marks for this question are for quality of mathematical exposition, with only a few marks for getting the answer right. Make sure to clearly explain and justify the steps you take. You may use results from the notes provided that you state them clearly and explain why they apply.*
:::