# Problem sheet 4  {.unnumbered #P04}


<!--
<style>
.fold-btn { 
  float: right; 
  margin: -12px 0 0 0;
}
</style>

<script type="text/javascript">
$(document).ready(function() {
  $folds = $(".myanswers");
  $folds.wrapInner("<div class=\"fold-blck\">"); // wrap a div container around content
  $folds.prepend("<button class=\"fold-btn\">Show solution</button>");  // add a button
  $(".fold-blck").toggle();  // fold all blocks
  $(".fold-btn").on("click", function() {  // add onClick event
    $(this).text($(this).text() === "Hide solution" ? "Show solution" : "Hide solution");  // if the text equals "Fold", change it to "Unfold"or else to "Fold" 
    $(this).next(".fold-blck").toggle("linear");  // "swing" is the default easing function. This can be further customized in its speed or the overall animation itself.
  })
});
</script>
-->




<style>
.myanswers { 
display: none !important;
}
</style>


\commfalse



::: {.mysummary}
You should attempt all these questions and write up your solutions in advance of your workshop in week 5 (Monday 22 or Tuesday 23 February) where the answers will be discussed.
:::



::::: {.myq}
**1.** Consider the Markov chain with state space $\mathcal S = \{1,2,3,4\}$ and transition matrix
\[ \mathsf P = \begin{pmatrix} 1 & 0 & 0 & 0 \\
1-\alpha & 0 & \alpha & 0 \\
0 & \beta & 0 & 1-\beta \\
0 & 0 & 0 & 1 \end{pmatrix}   \]
where $0 < \alpha, \beta < 1$.

:::: {.subq}
**(a)** Draw a transition diagram for this Markov chain.

::: {.myanswers data-latex=""}
*Solution.* 

```{tikz Q41, echo=FALSE, fig.align="center", fig.width=5, fig.cap="Transition diagram for Question 1.", cache = TRUE}
\usetikzlibrary{automata}
		\begin{tikzpicture}[shorten >=1pt,scale=1.2]
		\node[state] (1) at (0,0) {$1$};
		\node[state] (2) at (2,0) {$2$};
		\node[state] (3) at (4,0) {$3$};
		\node[state] (4) at (6,0) {$4$};
		
		\path[->] (2) edge node [above] {$1-\alpha$} (1);
		\path[->] (2) edge [bend left] node [above] {$\alpha$} (3);
        \path[->] (3) edge [bend left] node [below] {$\beta$} (2);
		\path[->] (3) edge node [above] {$1-\beta$} (4);
		
		\path[->] (1) edge [loop left]  node [left] {$1$} ();
		\path[->] (4) edge [loop right] node [right] {$1$} ();
		\end{tikzpicture}
```
:::
::::

:::: {.subq}
**(b)** What are the communicating classes for this Markov chain? Is the chain irreducible? Which classes are closed? Which states are absorbing?

::: {.myanswers data-latex=""}
*Solution.* 	Clearly $\{1\}$ and $\{4\}$ are closed communicating classes, so $1$ and $4$ are absorbing states. The other class, $\{2,3\}$ is not closed. Because there are multiple classes, the chain is not irreducible.
:::
::::

:::: {.subq}
**(c)** Find the hitting probability $h_{21}$ that, starting from state 2, the chain hits state 1.

::: {.myanswers data-latex=""}
*Solution.* 	It's clear that $h_{11} = 1$ and $h_{41} = 0$. Then, by conditioning on the first step, we have
	\begin{gather*}
	h_{21} = \alpha h_{31} + (1-\alpha) h_{11} = \alpha h_{31} + 1 - \alpha \\
	h_{31} = \beta h_{21} + (1-\beta) h_{41} = \beta h_{21} .
	\end{gather*}
	Substituting the second equation into the first, we get $h_{21} = \alpha\beta h_{21} + 1 - \alpha$, so
	\[ h_{21} = \frac{1-\alpha}{1-\alpha\beta}  . \]
:::
::::

:::: {.subq}
**(d)** What is the expected time, starting from state 2, to reach an absorbing state?

::: {.myanswers data-latex=""}
*Solution.* Let's write $A = \{1,4\}$ for the absorbing states, and $\eta_{iA}$ for the time to reach an absorbing state starting from state $i$. Clearly $\eta_{1A} = \eta_{4A} = 0$. By conditioning on the first step, we have
	\begin{gather*}
	\eta_{2A} = 1 + \alpha \eta_{3A} + (1-\alpha) \eta_{1A} = 1 + \alpha \eta_{3A}  \\
	\eta_{3A} = 1 + \beta \eta_{2A} + (1-\beta) \eta_{4A} = 1+\beta \eta_{2A} .
	\end{gather*}
	Substituting the second equation into the first gives
	$\eta_{2A}= 1 + \alpha + \alpha\beta \eta_{2A}$, so
	\[ \eta_{2A} = \frac{1+\alpha}{1-\alpha\beta}  . \]
:::
::::
:::::

::::: {.myq}
**2.**
Consider the Markov chain with state space $\mathcal S = \{1,2,3,4,5\}$ and transition matrix
\[ \mathsf P = \begin{pmatrix} 0 & \frac13 & \frac23 & 0 & 0 \\
				0 & 0 & 0 & \frac14 & \frac34 \\
				0 & 0 & 0 & \frac14 & \frac34 \\
				1 & 0 & 0 & 0 & 0 \\
				1 & 0 & 0 & 0 & 0 \end{pmatrix} . \]

:::: {.subq}
**(a)** Draw a transition diagram for this Markov chain.

::: {.myanswers data-latex=""}
*Solution.* 

```{tikz Q42, echo=FALSE, fig.align="center", fig.width=3, fig.cap="Transition diagram for Question 2.", cache = TRUE}
\usetikzlibrary{automata}
	\begin{tikzpicture}[shorten >=1pt,scale=1.8]
	\node[state] (2) at (0,2) {$2$};
	\node[state] (4) at (2,2) {$4$};
	\node[state] (5) at (0,0) {$5$};
	\node[state] (3) at (2,0) {$3$};
	\node[state] (1) at (1,1) {$1$};
	
	\path[->] (2) edge node [above]{$\frac14$} (4);
	\path[->] (2) edge node [left]{$\frac34$} (5);
	\path[->] (4) edge node [below right]{$1$} (1);
	\path[->] (3) edge node [right]{$\frac14$} (4);
	\path[->] (3) edge node [below]{$\frac34$} (5);
	\path[->] (5) edge node [above left]{$1$} (1);
	\path[->] (1) edge node [above right]{$\frac13$} (2);
	\path[->] (1) edge node [below left]{$\frac23$} (3);
	\end{tikzpicture}
```
:::
::::

:::: {.subq}
**(b)** Show that the chain is irreducible.

::: {.myanswers data-latex=""}
*Solution.* We have paths $1 \to 2 \to 4 \to 1$ and $1 \to 3 \to 5 \to 1$, so every state communicates with state 1, and by transitivity every state communicates with every other state.
:::
::::

:::: {.subq}
**(c)** What are the periods of the states?

::: {.myanswers data-latex=""}
*Solution.* Any path from $1$ to $1$ goes $1 \to \{2 \text{ or }3\} \to \{4 \text{ or }5\} \to 1$. So $p_{11}^{(n)} > 0$ if and only if $n$ is a multiple of $3$. So state $1$ has period $d_1 = 3$. Because the chain is irreducible, all other states have period $3$ too.
:::
::::

:::: {.subq}
**(d)** Find the expected hitting times $\eta_{i1}$ from each state $i$ to 1, and the expected return time $\mu_i$ to 1.

::: {.myanswers data-latex=""}
*Solution.* We could do this through a traditional conditioning on the first step argument. But in fact, the cyclic structure $1 \to \{2 \text{ or }3\} \to \{4 \text{ or }5\} \to 1$ makes it immediately clear that $\eta_11 = 0$, $\eta_{41}=\eta_{51} = 1$, $\eta_{21} = \eta_{31} = 2$, and $\mu_1 = 3$.
:::
::::
:::::


::::: {.myq}
**3.**

:::: {.subq}
**(a)** Show that every Markov chain on a finite state space $\mathcal S$ has at least one closed communicating class.

::: {.myanswers data-latex=""}
*Solution.* For communicating classes $C,D$, let's write $C \to D$ if there is an $i \in C$ and $j \in D$ with $i \to j$. Note that we can't have both $C \to D$ and $D \to C$ if $C$ and $D$ are distinct classes. This is because there would be $i_1, j_2 \in C$ and $j_1, i_2 \in D$ such that $i_1 \to j_1 \to i_2 \to j_2 \to i_1$, so they would be the same class. Let's also note that there are a finite number of classes $m$.
		
Pick a class $C_1$. If $C_1$ is closed, we are done; otherwise $C_1 \to C_2$ for some other class $C_2$. If $C_2$ is closed, we are done; otherwise $C_2 \to C_3$ for some class $C_3$ different to $C_1$ and $C_2$. (It can't be $C_1$ by the argument above.) We repeat: if $C_k$ is closed, we are done; otherwise there's a new class $C_{k+1}$ with $C_k \to C_{k+1}$. We eventually find a closed class: we either terminate before step $m$ at a closed class, or otherwise $C_m$ must be closed, as none of the previous $m-1$ classes can be accessible from it, by our earlier argument.
:::
::::

:::: {.subq}
**(b)** Give an example of a Markov chain that has no closed communicating classes.

::: {.myanswers data-latex=""}
*Solution.* By part (a), the state space must be infinite. Here's one example: take $\mathcal S = \mathbb Z$, and $X_{n+1} = X_n + 1$ with probability 1, so the Markov chain just marches up and up. There are no states $i$ and $j$ such that $i \leftrightarrow j$ (except for states communicating with themselves) so each state is a separate class. But clearly there is no absorbing state.
:::
::::
:::::

:::: {.myq}
**4.** Prove or give a counterexample: The period of a state $i$ is the smallest $d > 0$ such that $p_{ii}(d) > 0$.

::: {.myanswers data-latex=""}
*Solution.* The statement is not true. Here's one counterexample:

```{tikz counterexample, echo=FALSE, fig.align="center", fig.width=3, fig.cap="Transition diagram for a counterexample for Question 4.", cache = TRUE}
\usetikzlibrary{automata}
		\begin{tikzpicture}[scale=1.2]
		\node[state] (4) at (2.83,0) {A};
		\node[state] (5) at (4.83,0) {$0$};
		\node[state] (6) at (6.56,1) {B};
		\node[state] (7) at (6.56,-1) {C};
    \path[->] (4) edge[bend right] node [below]{$1$} (5);
    \path[->] (5) edge[bend right] node [above]{$\tfrac12$} (4);
    \path[->] (5) edge node [above left]{$\tfrac12$} (6);
    \path[->] (6) edge node [right]{$1$} (7);
    \path[->] (7) edge node [below left]{$1$} (5);
		\end{tikzpicture}
```

We see that $p_{00} = p_{00}(1) = 0$, but $p_{00}(2) = \frac12 > 0$ (going via A) and $p_{00}(3) = \frac12 > 0$ (going via B and C). Hence $d_0 \leq \text{gcd}\{2,3\} = 1$, so $d_0 = 1$, contradicting the statement in the question.
:::
::::

:::: {.myq}
**5.** Consider the simple random walk with $p < \frac12$, and let $i > 0$. Show that
$\eta_{i0} = i/(q-p)$.

::: {.myanswers data-latex=""}
*Solution.* By conditioning on the first step, we have
\[ \eta_{i0} = 1 + p\eta_{i+1\,0} + q\eta_{i-1\,0} . \]
Either by solving this linear difference equation directly or by remembering the solution from when we did expected duration of the gambler's ruin, the general solution is
\[ \eta_{i0} = A + B\rho^i + \frac{i}{q-p} , \]
where $\rho = q/p > 0$.

We have one initial condition $\eta_{00} = 0$ (since we're "already there"). This gives $0 = A + B$, so we have
\[ \eta_{i0} = -B + B\rho^i + \frac{i}{q-p} = B(\rho^i - 1) + \frac{i}{q-p} . \]

We now have to use the principle of the minimum non-negative solution. Since $\rho > 1$, we also have $\rho^i - 1 > 0$. Hence $B$ must be non-negative, to ensure the whole solution is  non-negative, but we want $B$ to be as small as possible, to ensure minimality. Hence we must have $B = 0$, finally giving the solution
\[ \eta_{i0} = \frac{i}{q-p} \]
as desired.
:::
::::

::::: {.myq}
**6.** Consider the Markov chain with the following transition matrix and transition diagram:

::::: {style="display: flex;"}
::: {}
```{tikz Q45, echo=FALSE, fig.align="center", fig.width=2.5, fig.cap="Transition diagram for Question 6.", cache = TRUE}
\usetikzlibrary{automata}
		\begin{tikzpicture}[scale=1.3]
		\node[state] (1) at (0,0) {$1$};
		\node[state] (2) at (1.41,1.41) {$2$};
		\node[state] (3) at (1.41,-1.41) {$3$};
		\node[state] (4) at (2.83,0) {$4$};
		
		\path[->] (1) edge[bend left] node [above left]{$\frac14$} (2);
		\path[->] (2) edge[bend left] node [above right]{$\frac12$} (4);
		\path[->] (4) edge[bend left] node [below right]{$\frac23$} (3);
		\path[->] (3) edge[bend left] node [below left]{$\frac12$} (1);
		\path[->] (1) edge[bend left] node [below left]{$\frac12$} (3);
		\path[->] (3) edge[bend left] node [below right]{$\frac12$} (4);
		\path[->] (4) edge[bend left] node [above right]{$\frac13$} (2);
		\path[->] (2) edge[bend left] node [above left]{$\frac12$} (1);
		\path[->] (1) edge node [above]{$\frac14$} (4);
		\end{tikzpicture}
```
:::

::: {}
\[ \mathsf P = \begin{pmatrix} 0 & \frac14 & \frac12 & \frac14 \\
               \frac12 & 0& 0& \frac12 \\
               \frac12 & 0& 0& \frac12 \\
               0 & \frac13 & \frac23 & 0 \end{pmatrix} \]
:::
::::

The Markov chain starts from state 1.

:::: {.subq}
**(a)** What is the probability that we hit state 2 before we hit state 3?

::: {.myanswers data-latex=""}
*Solution.* Write $k_i$ for the probability we hit state 2 before state 3 starting from $i$. Then clearly $k_2 = 1$ (since we've hit 2 first) and $k_3 = 0$ (since we've hit 3 first). Further, by conditioning on the first step, $k_4 = \frac13 k_2 + \frac23 k_3 = \frac13$, and
\[ k_1 = \tfrac14 k_2 + \tfrac12k_3 + \tfrac14 k_4   = \tfrac14 + \tfrac14 k_4 = \tfrac14 + \tfrac14\tfrac13 = \tfrac13 . \]
The desired solution is $k_1 = \frac13$.
:::
::::

:::: {.subq}
**(b)** What is the expected time until we hit a state in the set $\{2,3\}$?

::: {.myanswers data-latex=""}
*Solution.* Let $A = \{2,3\}$, and $\eta_{iA}$ be the expected time until hitting the first of states $2$ and $3$ starting from $i$. Clearly $\eta_{2A} = \eta_{3A} = 0$. By conditioning on the first step, $\eta_{4A} = 1+ \frac13 \eta_{2A} + \frac23 \eta_{3A} = 1$, and
\[ \eta_{1A} = 1 + \tfrac14 \eta_{2A} + \tfrac12\eta_{3A} + \tfrac14 \eta_{4A} = 1 + \tfrac14 = \tfrac54 .        \]
The desired solution is $\eta_{1A} = \tfrac54$.
:::
::::
:::::



